# Prompt itself
[character]
success_symbol = "[><>](bold green)"
error_symbol = "[><>](bold red)"
vimcmd_symbol = "[<><](bold green)"
vimcmd_replace_one_symbol = "[<><](bold purple)"
vimcmd_replace_symbol = "[<><](bold purple)"
vimcmd_visual_symbol = "[<><](bold yellow)"

# Git
[git_status]
ahead = "↑"
behind = "↓"
diverged = "↕"
deleted = "×"

[git_branch]
symbol = " "

# Package version
[package]
symbol = " "

# OS environment
[directory]
read_only = " 󰉐 "

[sudo]
symbol = "󱑷 "
disabled = false

# Languages
[aws]
symbol = " "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = "⌘ "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[custom.make]
symbol = " "
detect_files = [ "GNUmakefile", "makefile", "Makefile" ]
style = "bold yellow"
format = "via [$symbol($output )]($style)"

[meson]
symbol = "󰯙 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[spack]
symbol = "🅢 "

# OS
[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
#HardenedBSD = ""
Illumos = "󱗆 "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = "󰺡 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "
