# Prompt itself
format = "$all$username$hostname $directory$character"

[hostname]
format = "[@$ssh_symbol$hostname]($style)"

[username]
format = "[$user]($style)"
show_always = true

[character]
error_symbol = "[>](bold red)"
success_symbol = "[>](bold green)"


# Git
[git_status]
ahead = "↑"
behind = "↓"
diverged = "↕"
deleted = "×"

[git_branch]
symbol = " "


# Package version
[package]
symbol = " "


# Languages
[custom.make]
symbol = " "
detect_files = [ "GNUmakefile", "makefile", "Makefile" ]
style = "bold yellow"
format = "via [$symbol($output )]($style)"


# OS
[directory]
read_only = " 󰉐 "

[sudo]
symbol = "󱑷 "
disabled = false

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
#HardenedBSD = ""
Illumos = "󱗆 "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = "󰺡 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "
