[background]
path = "/data/pictures/wallpapers/82072674_p0.png"

[env]
MOZ_ENABLE_WAYLAND=1

[GTK]
application_prefer_dark_theme = true
font_name = "Inter 16"
theme_name = "Catppuccin-Macchiato-Standard-Sapphire-Dark"
icon_theme_name = "Papirus-Dark"
cursor_theme_name = "posy-white"

[commands]
reboot = [ "systemctl", "reboot" ]
poweroff = [ "systemctl", "poweroff" ]
