[background]
path = "/data/pictures/wallpapers/81845221_p0.png"
fit = "Fill"

[env]
GRIM_DEFAULT_DIR = "$HOME/Картинки/grim"
MOZ_ENABLE_WAYLAND = "1"
QT_STYLE_OVERRIDE = "kvantum"
QT_QPA_PLATFORMTHEME = "gtk3"

[GTK]
application_prefer_dark_theme = true
font_name = "Inter 12"
theme_name = "Catppuccin-Mocha-Standard-Sky-Dark"
icon_theme_name = "Papirus-Dark"
cursor_theme_name = "posy-white"

[commands]
reboot = [ "systemctl", "reboot" ]
poweroff = [ "systemctl", "poweroff" ]
